src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    public const ROLE_STUDENT = 'ROLE_STUDENT';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Ticket::class)]
    private Collection $tickets;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Session $session = null;

    #[ORM\Column]
    private ?bool $authorized = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
        $this->roles = [self::ROLE_STUDENT];
        $this->created_at= new \DateTimeImmutable();
        $this->updated_at= new \DateTimeImmutable();
        $this->authorized= false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_STUDENT
        $roles[] = 'ROLE_STUDENT';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setOwner($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getOwner() === $this) {
                $ticket->setOwner(null);
            }
        }

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): static
    {
        $this->session = $session;

        return $this;
    }

    public function isAuthorized(): ?bool
    {
        return $this->authorized;
    }

    public function setAuthorized(bool $authorized): static
    {
        $this->authorized = $authorized;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\StatusRepository;
use App\Repository\TicketRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    #[IsGranted('ROLE_STUDENT')]
    #[Route('/', name: 'home')]
    public function index(TicketRepository $ticketRepository, StatusRepository $statusRepository): Response
    {
        $user = $this->getUser();
        $userId = $user->getId();

        $status = $statusRepository->findAll();
        $statusId = $status[0]->getId();

        // Ici requete pour les autres ticket;

        $ticket = $ticketRepository->findTicketsWhereStatusAndExcludedUser($userId, $statusId);

        // dd($ticket);

        // ICI REQUETE POUR les userTickets

        $userTickets = $ticketRepository->findBy(
            ['owner' => $userId ]
        );

        // dd($userTickets);

        // $products = $repository->findBy(
        //     ['name' => 'Keyboard'],
        //     ['price' => 'ASC']
        // );

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController', 
            'tickets' => $ticket,
            'userTickets' => $userTickets
        ]);
    }
}

templates/main/index.html.twig
{% extends 'baseDashboard.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}

	<div id="image-modal" style="display: none; position: fixed; z-index: 100; left: 0; top: 0; width: 100%; height: 100%; background-color: rgba(0,0,0,0.5); align-items: center; justify-content: center;">
		<img id="modal-image" style="max-width: 90%; max-height: 90%;">
	</div>

	<main class="container">
	
		<div class="col-12 my-4">
		{{ include('search/_form.html.twig') }}
		</div>
		<div class="col-12 d-flex justify-content-between align-items-center my-2">
			<h1>Ticket party !</h1>
			<a href="{{ path('app_ticket_new') }} " class="btn perso-button-main mt-2">Créer nouveau ticket</a>
		</div>

		<section class="container">
			<div class="row justify-content-center">
				{% for ticket in tickets %}
					{% if ticket.id != ticket.owner.id %}
						<div class="col-12 col-lg-6 col-xl-4 p-2">
							<div class="card h-100">
								<div class="card-body">
									<p class="d-flex justify-content-between">Ticket #{{ ticket.id }}
										<span class="badge fs-5 bg-main-color">
											{{ ticket.status.name}}
										</span>
									</p>
									{% if ticket.image is not null %} 
										<img src="{{ asset('uploads/images/' ~ ticket.image) }}" class="card-img-top clickable-image" alt="...">
									{% endif %}
									

									<div class="d-flex justify-content-between p-2 mt-2">
									<div>
										<span class="badge fs-5 bg-main-color">{{ ticket.owner.session.name }}</span>
									</div>
										<p>
											{% if ticket.priority %}
												<span class="badge bg-warning fs-6">Élevée</span>
											{% else %}
												<span class="badge bg-success fs-6">Normale</span>
											{% endif %}
										</p>
									</div>
									<h2>{{ ticket.owner.firstname }}
										{{ ticket.owner.lastname }}</h2>
									<div class="d-flex justify-content-between">
										<p class="card-text">Avec
											{{ ticket.technology.name }}</p>
										<p class="d-flex justify-content-end">
											{% if ticket.createdAt %}
												<span>
												{# Créer le : #}
													{{ ticket.createdAt ? ticket.createdAt|date('d-m-Y H:i:s') : '' }}</span>
											{% else %}
												<span>Mis à jour le :
													{{ ticket.updatedAt ? ticket.updatedAt|date('Y-m-d H:i:s') : '' }}</span>
											</p>
										{% endif %}
									</div>
									<p>{{ ticket.subject }}</p>
								</div>
								<div class="text-center mb-3">
									<a href="{{ path('app_ticket_show', {'id': ticket.id}) }}" class="btn perso-button-main ">
										Aider mon camarade
									</a>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</section>
			
		<div>
			<h2>Mes tickets</h2>
		</div>
		<section class="container">
			<div class="row justify-content-center">
				{% for ticket in userTickets %}
					{% if ticket.id != ticket.owner.id %}
						<div class="col-12 col-lg-4 p-2">
							<div class="card h-100">
								<div class="card-body">
									<p class="d-flex justify-content-between">Ticket #{{ ticket.id }}
										{# Status #}
										<span class="badge bg-main-color fs-6">{{ ticket.status.name }}</span>
									</p>
									{% if ticket.image is not null %}
										<img src="{{ asset('uploads/images/' ~ ticket.image) }}" class="card-img-top clickable-image" alt="...">
									{% endif %}
									<p>
										{% if ticket.priority %}
											<span class="badge bg-warning fs-6">Élevée</span>
										{% else %}
											<span class="badge bg-success fs-6">Normale</span>
										{% endif %}
									</p>
									{# <h5 class="card-title">Session
										<span class="badge fs-5 bg-main-color">{{ ticket.owner.session ? ticket.owner.session.name : '' }}</span>
									</h5>
									<h2>{{ ticket.owner.firstname }}
										{{ ticket.owner.lastname }}!</h2> #}
									<div class="d-flex justify-content-between">
										<p class="card-text">
										{# Avec #}
											{{ ticket.technology.name }}</p>
										<p class="d-flex justify-content-end">
											{% if ticket.createdAt %}
												<span>Créer le :
													{{ ticket.createdAt ? ticket.createdAt|date('Y-m-d H:i:s') : '' }}</span>
											{% else %}
												<span>Mis à jour le :
													{{ ticket.updatedAt ? ticket.updatedAt|date('Y-m-d H:i:s') : '' }}</span>
											</p>
										{% endif %}
									</div>
									<p>{{ ticket.subject }}</p>
								</div>
								<div class="text-center mb-3">
									<a href="{{ path('app_ticket_show', {'id': ticket.id}) }}" class="btn perso-button-main col-5">
										Voir
									</a>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</section>
		
	</main>
{% endblock %}